require('config.options')
require('config.keymaps')

require('plugins.init')
require('plugins.cmp')
require('plugins.lsp')
require('plugins.treesitter')
require('plugins.autopairs')
require('plugins.explorer')
require('plugins.telescope')
require('plugins.lualine')
require('plugins.bufferline')
require('plugins.bufremove')
require('plugins.colorscheme')
require('plugins.laravel')
