require('config.autocmd')
require('config.keymaps')
require('config.options')

require('plugins.init')
require('plugins.autopairs')
require('plugins.bufferline')
require('plugins.bufremove')
require('plugins.cmp')
require('plugins.colorscheme')
require('plugins.explorer')
require('plugins.laravel')
require('plugins.lsp')
require('plugins.lualine')
require('plugins.telescope')
require('plugins.treesitter')
require('plugins.gitsigns')
